[package]
name = "thaler-study"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "matrix-multiplication",
    "multilinear-extensions",
    "triangle-counting",
    "sum-check-protocol",
]
