[workspace]

resolver = "2"

members = [
    "gkr-protocol",
    "fiat-shamir",
    "matrix-multiplication",
    "multilinear-extensions",
    "relaxed-pcs",
    "triangle-counting",
    "sum-check-protocol",
]
